# -*- coding: utf-8 -*-
"""UniAUDIO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b0O56psrHX_3mZPICaOa0fQoblDTHiqX
"""

# ==========================================
# BLOCK 1: ENVIRONMENT & AUDIO PIPELINE
# ==========================================
!pip install -q transformers openai faiss-cpu gradio librosa soundfile numpy scipy torch

import os
import torch
import numpy as np
import librosa
import soundfile as sf
import faiss
from transformers import WhisperProcessor, WhisperModel, WhisperForConditionalGeneration
from openai import OpenAI
import gradio as gr
import time
import json

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

class AudioPipeline(torch.nn.Module):
    def __init__(self, whisper_model_name="openai/whisper-base", target_llm_dim=4096):
        super().__init__()
        print("Initializing Local Audio Pipeline...")
        self.processor = WhisperProcessor.from_pretrained(whisper_model_name)

        # Audio feature encoder
        self.encoder = WhisperModel.from_pretrained(whisper_model_name).encoder.to(device)
        self.encoder.eval()

        # Semantic text extractor (The fix we added)
        self.transcriber = WhisperForConditionalGeneration.from_pretrained(whisper_model_name).to(device)
        self.transcriber.eval()

        whisper_dim = self.encoder.config.d_model
        self.projection = torch.nn.Sequential(
            torch.nn.Linear(whisper_dim, target_llm_dim),
            torch.nn.LayerNorm(target_llm_dim),
            torch.nn.SiLU(),
            torch.nn.Dropout(0.1)
        ).to(device)
        self.projection.eval()

    def preprocess_audio(self, audio_path, target_sr=16000):
        y, sr = librosa.load(audio_path, sr=target_sr)
        y = librosa.util.normalize(y)
        y_trimmed, _ = librosa.effects.trim(y, top_db=20)
        return y_trimmed, target_sr

    @torch.no_grad()
    def forward_encoder(self, waveform):
        inputs = self.processor(waveform, return_tensors="pt", sampling_rate=16000)
        input_features = inputs.input_features.to(device)
        hidden_states = self.encoder(input_features).last_hidden_state
        projected = self.projection(hidden_states)
        return projected, hidden_states

    @torch.no_grad()
    def build_representation(self, waveform, sr, hidden_states):
        """Calculates stats AND extracts the spoken text."""
        duration = len(waveform) / sr
        rms = librosa.feature.rms(y=waveform)[0]
        zcr = librosa.feature.zero_crossing_rate(y=waveform)[0]

        # Extract Semantic Text
        inputs = self.processor(waveform, return_tensors="pt", sampling_rate=16000).to(device)
        predicted_ids = self.transcriber.generate(inputs.input_features)
        transcript = self.processor.batch_decode(predicted_ids, skip_special_tokens=True)[0].strip()

        return {
            "transcript": transcript if transcript else "[No speech detected]",
            "duration_seconds": round(duration, 2),
            "mean_energy": round(float(np.mean(rms)), 4),
            "max_energy": round(float(np.max(rms)), 4),
            "speaking_rate_index": round(float(np.mean(zcr)), 4)
        }

audio_pipeline = AudioPipeline()
print("Audio Pipeline ready.")

# ==========================================
# BLOCK 2: OPENROUTER ENGINE
# ==========================================

class SystemOrchestrator:
    def __init__(self, openrouter_key="YOUR_API_KEY", model_name="openrouter/free"):
        self.client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=openrouter_key
        )
        self.model_name = model_name
        self.memory_dim = 384
        self.index = faiss.IndexFlatL2(self.memory_dim)
        self.memory_store = []
        self.conversation_history = []
        self.logs = []

    def _get_text_embedding(self, text):
        hashed = np.zeros(self.memory_dim, dtype=np.float32)
        for i, char in enumerate(text[:self.memory_dim]):
            hashed[i % self.memory_dim] = ord(char) % 13
        norm = np.linalg.norm(hashed)
        return (hashed / norm if norm > 0 else hashed).astype('float32')

    def add_to_long_term_memory(self, user_query, assistant_response, metadata):
        record_text = f"Query: {user_query} | Response: {assistant_response}"
        vector = self._get_text_embedding(record_text).reshape(1, -1)
        self.index.add(vector)
        self.memory_store.append(record_text)

    def retrieve_memories(self, query, top_k=2):
        if self.index.ntotal == 0:
            return "No previous memories found."
        vector = self._get_text_embedding(query).reshape(1, -1)
        distances, indices = self.index.search(vector, min(top_k, self.index.ntotal))
        return "\n".join([self.memory_store[idx] for idx in indices[0] if idx < len(self.memory_store)])

    def route_task(self, user_intent, audio_stats):
        intent = user_intent.lower()
        if "transcribe" in intent: return "TRANBCRIPTION_MODE"
        elif "translate" in intent: return "TRANSLATION_MODE"
        elif "emotion" in intent: return "EMOTION_ANALYSIS_MODE"
        elif "summary" in intent: return "AUDIO_SUMMARIZATION_MODE"
        return "GENERAL_AUDIO_QA_MODE"

    def execute_unified_reasoning(self, user_query, audio_stats, task_mode):
        start_time = time.time()
        memories = self.retrieve_memories(user_query)

        prompt = f"""
        [UNIFIED AUDIO INTELLIGENCE AGENT]

        AUDIO TRANSCRIPT: "{audio_stats['transcript']}"

        TONE METADATA:
        - Duration: {audio_stats['duration_seconds']}s
        - Energy Level: {audio_stats['mean_energy']}
        - Speaking Rate (ZCR): {audio_stats['speaking_rate_index']}

        ROUTED MODE: {task_mode}
        HISTORICAL MEMORIES: {memories}

        USER INSTRUCTION: {user_query}

        Please synthesize a response. Rely primarily on the semantic meaning in the AUDIO TRANSCRIPT to answer the instruction. Use the TONE METADATA only to infer the speaker's emotional state or delivery style.
        """

        try:
            response = self.client.chat.completions.create(
                model=self.model_name,
                messages=[
                    {"role": "system", "content": "You are a robust Audio Intelligence agent. Directly answer the user's prompt based on the provided transcript and audio data."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.3
            )
            assistant_reply = response.choices[0].message.content
        except Exception as e:
            assistant_reply = f"OpenRouter API Error: {str(e)}"

        latency = time.time() - start_time
        metric_log = {"timestamp": time.time(), "latency_seconds": round(latency, 3), "query": user_query}
        self.logs.append(metric_log)
        self.add_to_long_term_memory(user_query, assistant_reply, audio_stats)

        return assistant_reply, metric_log

engine = SystemOrchestrator()
print("OpenRouter Routing & Reasoning Matrix ready.")

# ==========================================
# BLOCK 3: SPEECH SYNTHESIS & GRADIO UI
# ==========================================

def text_to_speech_approximation(text_content, output_path="response.wav"):
    sr = 16000
    duration = 1.0
    t = np.linspace(0, duration, int(sr * duration), endpoint=False)
    wave = 0.4 * np.sin(2 * np.pi * 440 * t)
    sf.write(output_path, wave, sr)
    return output_path

def process_runtime_event(input_audio, user_text, target_task):
    if input_audio is None:
        return "Please upload or record an audio snippet.", None, "No operations logged."
    try:
        clean_wave, sr = audio_pipeline.preprocess_audio(input_audio)
        projected, hidden = audio_pipeline.forward_encoder(clean_wave)
        audio_stats = audio_pipeline.build_representation(clean_wave, sr, hidden)

        task_mode = engine.route_task(user_text if user_text else target_task, audio_stats)
        execution_query = user_text if user_text else f"Execute task: {target_task}"

        reply, metrics = engine.execute_unified_reasoning(execution_query, audio_stats, task_mode)
        generated_audio_file = text_to_speech_approximation(reply)

        log_view = f"--- DIAGNOSTICS ---\n{json.dumps(metrics, indent=2)}\n\n--- AUDIO PAYLOAD ---\n{json.dumps(audio_stats, indent=2)}"
        return reply, generated_audio_file, log_view

    except Exception as error:
        return f"Pipeline Error encountered: {str(error)}", None, "Execution broken."

with gr.Blocks(title="Audex Hybrid-MAS Workbench") as interface:
    gr.Markdown("# 🎙️ Audex Hybrid-MAS (OpenRouter Edition)")

    with gr.Row():
        with gr.Column():
            audio_input = gr.Audio(sources=["microphone", "upload"], type="filepath", label="Input Signal Stream")
            text_input = gr.Textbox(placeholder="Ask a question (e.g., 'What did I say?' or 'Summarize this')", label="Instruction Criteria Input")
            task_dropdown = gr.Dropdown(
                choices=["General Audio QA Mode", "Transcription Mode", "Translation Mode", "Emotion Analysis Mode", "Audio Summarization Mode"],
                value="General Audio QA Mode",
                label="Fallback Architectural Router Configuration"
            )
            submit_button = gr.Button("Execute Multimodal Pipeline Flow")

        with gr.Column():
            text_output = gr.Textbox(label="Unified Reasoning Response Vector")
            audio_output = gr.Audio(label="Synthesized Response Stream", type="filepath")
            metrics_panel = gr.Code(label="Pipeline Architecture Diagnostics & Feature Logs", language="json")

    submit_button.click(
        fn=process_runtime_event,
        inputs=[audio_input, text_input, task_dropdown],
        outputs=[text_output, audio_output, metrics_panel]
    )

interface.launch(debug=True)

